### ISSUE TITLE
No bash?

### ISSUE THREAD

**Issue by eflemingtra** [b3vis/docker-borgmatic#28]
Hi,

First, just wanted to say thanks for your docker image. I've used your docker compose file and your config.yaml and crontab.txt as a starting point. However, I'm unable to SSH into the container itself using `sudo docker exec -it borgmatic /bin/bash`. Does this mean bash isn't within the container?

If so, I'm unsure how I can verify backups or even restore using the docker container. I'm sure I'm missing something completely obvious but would appreciate your thoughts.

Additionally, does your docker container automatically create a repository? Or is it just the location for said repository (again, without being able to SSH into the container, I'm unsure how this is possible).

Thank you very much

**Comment by witten** [comment]
I'm not the container's author, but you can use Alpine's built-in `sh` instead of `bash`! Example: `sudo docker exec -it borgmatic sh`

I don't think the container auto-creates a repository. But you can do that once you `exec` into that with `borgmatic init` / `borgmatic --init`. Similar for verifying backups. Once you're `exec`'d in, `borgmatic list` (or `--list`), etc. are available.

**Comment by eflemingtra** [comment]
That worked, thank you very for your help, I new there must be a simple solutions.

**Comment by b3vis** [comment]
Thanks @witten 🤘🏽Let us know if you have any other issues @eflemingtra
