### ISSUE TITLE
1.1.10 didn't make it to dockerhub?

### ISSUE THREAD

**Issue by toastie89** [b3vis/docker-borgmatic#31]
Hi b3vis! The Dockerfile on dockerhub [1] seems to be not up-to-date with the github repository. In github we have BORG_VERSION=1.1.10, while dockerhub shows BORG_VERSION=1.1.9 and some other changes are not updated. Any reason to hold the latest version back?

[1] https://hub.docker.com/r/b3vis/borgmatic/dockerfile

**Comment by b3vis** [comment]
Weird, so it looks like the build on Docker hub failed. I've kicked off a manual build for the image tag so hopefully it will build successfully this time. It built locally with no issues.

**Comment by b3vis** [comment]
I must have remembered incorrectly, it doesn't build locally as alpine have updated their `python3` package so instead of installing `3.6` it was now using `3.7` and the line 

`COPY --from=builder /usr/lib/python3.6/site-packages /usr/lib/python3.6/` was making it fail.

Updated these paths in the Dockerfile and it now builds locally. I've deleted the release and re-created it and have kicked the docker hub to get it to build the new image. Sorry about that.

Happy pulling! 🎉
