### ISSUE TITLE
Issue No such file or directory /mnt/borg-repository/config

### ISSUE THREAD

**Issue by Kayoku** [b3vis/docker-borgmatic#36]
Hi,

Is it possible to update the version of borg for fix [this issue](https://projects.torsion.org/witten/borgmatic/issues/201) ?
I think we need at least [this merge PR](https://github.com/borgbackup/borg/pull/4461).
If not, do you have a temporary fix for this ? Because your docker-borgmatic isn't usable now....

Thanks

**Comment by b3vis** [comment]
Hi,

The container is running the current latest stable Borg, I'm not even 100% sure what the issue is from the issue link you've posted? Please provide more details and I will do my best.

From what I understand this image is working fine, this is just if people want to run a Borg repository without a password, I wouldn't say the image isn't usable...
