### ISSUE TITLE
crontab in /etc/borgmatic.d/crontab.txt

### ISSUE THREAD

**Issue by hrv231** [b3vis/docker-borgmatic#65]
Hello,

I followed your documentation and now I have a running docker doing backups, everything seems to be good, except that today I noticed that the docker was doing a backup when it wasn't supposed to.
I checked my crontabs.txt file and everything was set correctly there, so I couldn't understand why it was doing a backup.
Then I ran crontab -l and it showed me a different crontab config, it was showing me the first crontab config I did when I was testing the docker.

Following the borgmatic original docs I did a chmod +x to my /etc/borgmatic.d/crontab.txt and then I manually copy the file to /etc/crontabs/root

Can you please update your documentation explaining a little bit more about the permissions on the crontab.txt file and how exactly the file inside /etc/borgmatic.d/ sync with cron from /etc/crontabs/ ?

Maybe after every change I do to the crontab.txt I had to run some commands that I don't know yet, if that's the case, please put it in your documentation.

To be clear, the file that I want to be changing from time to time is the crontab.txt, like your docs says...

Thank you for your time, it is a great docker.

**Comment by MarkJonas** [comment]
@hrv231 Did you stop and delete the container and then start a new one? The container imports your custom crontab during the initial startup. This is pretty much normal behavior for most containers.

**Comment by hrv231** [comment]
> 
> 
> @hrv231 Did you stop and delete the container and then start a new one? The container imports your custom crontab during the initial startup. This is pretty much normal behavior for most containers.

Yes I did, and that works, but my point is, it is better to make changes on that .txt file and the change will get updated into the crontab, without having to reboot the docker.

**Comment by b3vis** [comment]
I have experience running cron in containers professionally and it’s almost always best to have the crontab loaded in upon container creation instead of trying to rely on a mechanism to continually try and update the crontab. 

The “easy” fix to do it the way you’ve asked would be to start cron as root in the container then have a cron job run as root that does a ‘crontab -u backups /etc/borgmatic/crontab.txt’

This will read in your user crontab every X time and keep the user backups crontab updated as you ask.

This would bring even more complication because then Borg isn’t running as root, users would have to ensure the backups user is created using a uid:gid they have on their host system which can read the files.

I don’t think people change their crontab enough to warrant the work to implement this as it’s not difficult to use docker compose with the provided example to just docker-compose down and then up -d again after you edit your crontab
